enum ActionEnum {
  SALE,
  VOID,
  APP_INIT,
  UPI_QR,
  UPI_VPA,
  BHARAT_QR,
  STATIC_QR,
  UPI_QR_CHECK_STATUS,
  BHARAT_QR_CHECK_STATUS,
  VPA_CHECK_STATUS,
  SMS_PAY,
  CARD_TRANSACTION_HISTORY,
  NON_CARD_TRANSACTION_HISTORY
}
